language: node_js
node_js:
  - node
cache:
  apt: true
  directories:
    - node_modules
env:
  - SERVER_IP_ADDRESS=23.105.194.254
addons:
  ssh_known_hosts:
    - 23.105.194.254
script:
  - npm install
after_script:
  - npm run build
